# Generated by Django 4.0.3 on 2022-04-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0002_remove_estudiante_id_remove_profesor_id_curso_camada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='nombre',
            field=models.CharField(default='Jirafales', max_length=40),
            preserve_default=False,
        ),
    ]
